### ISSUE TITLE
Add map:room:delete, map:room:delete:id

### ISSUE THREAD

**Issue by michael-donat** [michael-donat/tf-mapper#43]
map:room:delete - deletes active room
map:room:delete:id - deletes room by id

**Comment by x1a0** [comment]
Hi,

Thanks for this really really awesome project!

I've been trying to make it work with BatMud. It seems `map:room:delete` works well but when I specified `:id` there it did not work...

**Comment by x1a0** [comment]
I found `map:undo` was the command I actually looked for.

But still, delete-room-by-id seems not work.
